name: testform
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  appwrite: ^12.0.1
  archive: ^3.5.0
  dart_openai: ^5.1.0
  data_table_2: ^2.5.12
  dio: ^5.4.2+1
  email_validator: ^2.1.17
  fluent_ui: ^4.8.6
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_math_fork: ^0.7.2
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  html: ^0.15.4
  http: ^1.2.1
  ipaddr: ^2.1.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  markdown: ^7.2.2
  markdown_widget: ^2.3.2+6
  path: ^1.9.0
  path_provider: ^2.1.3
  protobuf: ^3.1.0
  provider: ^6.1.2
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  rps: ^0.7.0
  sqflite: ^2.3.3
  system_theme: ^2.3.1
  uuid: ^4.4.0
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true


scripts:
  gen: dart run build_runner build --delete-conflicting-outputs
